#!/bin/bash

set -e

NAME="mayan-swap"
SONAME="mayanswap"
VERSION="v0.2"

BUILD_FILE="./src/program-c/src/$SONAME/build-info.h"

COUNTER=`echo $(cat ./b_counter)+1 | bc`
echo $COUNTER > ./b_counter
TIME=`date +%s`

echo """
// This file is autogenerated. do not modify :))
#ifndef _BUILD_INFO_H_
#define _BUILD_INFO_H_

#define BUILD_NAME $NAME
#define BUILD_VER $VERSION
#define BUILD_COUNTER $COUNTER
#define BUILD_TIME $TIME
#define BUILD_TEXT \"$NAME $VERSION (build $COUNTER at $TIME)\"

#endif //_BUILD_INFO_H_
""" > $BUILD_FILE

#V=1 make -C ./src/program-c mayanbridge clean
#cp mayanbridge-keypair.json dist/program/mayanbridge-keypair.json

if [[ -f dist/program/$SONAME.so ]]; then
	echo "Removing old files"
	rm dist/program/$SONAME.so
	rm dist/program/$SONAME/*
fi
V=1 make -C ./src/program-c $SONAME
