
// This file is autogenerated. do not modify :))
#ifndef _BUILD_INFO_H_
#define _BUILD_INFO_H_

#define BUILD_NAME mayan-swap
#define BUILD_VER v0.2
#define BUILD_COUNTER 93
#define BUILD_TIME 1656526739
#define BUILD_TEXT "mayan-swap v0.2 (build 93 at 1656526739)"

#endif //_BUILD_INFO_H_

